### ISSUE TITLE
Decor with transient servive and delegate. Could not find a parameterless constructor

### ISSUE THREAD

**Issue by robertgm** [lawrence-laz/Decor.NET#19] opened 2024-06-27 15:06 UTC
Cannot get service inside Transient registration of service.
Project on Git with sample: [DecorTransientDelegateBug](https://github.com/robertgm/DecorTransientDelegateBug)

Class with Decor attribute:
```
public class ServiceBLL : IServiceBLL
{
    private readonly IServiceDependencyBLL serviceDependencyBLL;

    public ServiceBLL(IServiceDependencyBLL serviceDependencyBLL)
    {
        this.serviceDependencyBLL = serviceDependencyBLL;
    }

    [Decorate(typeof(CacheDecorator))]
    public string GetValueB()
    {
        return "dependency" + this.serviceDependencyBLL.GetValueA();
    }
}
```

Service registration:
```
builder.Services.AddControllers();

builder.Services.AddDecor();
builder.Services.AddSingleton<CacheDecorator>();
builder.Services.AddSingleton<IServiceDependencyBLL, ServiceDependencyBLL >().Decorated();
builder.Services.AddSingleton<ServiceBLL>().Decorated();

builder.Services.AddTransient<Func<string, IServiceBLL>>(serviceProvider => account => {
    switch (account)
    {
        case "countryA":
            return serviceProvider.GetService<ServiceBLL>(); // error
        default:
            throw new Exception("Country does not exist.");
    }
});
```
When application calls `serviceProvider.GetService<ServiceBLL>();` it get error:
```
 Castle.DynamicProxy.InvalidProxyConstructorArgumentsException: 'Can not instantiate proxy of class: DecorTransientDelegateBug.BLL.ServiceBLL.
Could not find a parameterless constructor.'
```
I need to have constructor with parameter because I need to use other service that have to be injected in ServiceBLL class.

**Comment by lawrence-laz** [comment] 2024-06-27 18:48
Decorating concrete types requires them to have a parameterless constructor. This is a limitation of the Castle Core library (discussed here https://github.com/castleproject/Core/issues/532).

As a pretty simple workaround you can register `ServiceBLL` as an interface, which will not require a parameterless constructor:
<img width="915" alt="image" src="https://github.com/lawrence-laz/Decor.NET/assets/8823448/94ae90dc-fac2-4798-8973-47bfcbcc1b92">

Closing as a duplicate of #4

**Closed as completed by lawrence-laz** 2024-06-27 18:48 UTC
